title: ChaosML
name:  ML;DL
email:       csheth !! cs.stonybrook.edu
author:      Chintak Sheth
description: >
    Notes on machine learning and deep learning.
date_format: "%b %-d, %Y"

master_repo: false
url: "chintak.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist']

paginate: 5

logo:             favicon.ico
disqus_shortname: chintaksheth

hashtag: ChintakShethBlog

owner:
  name:           chintak sheth
  avatar:         ""
  email:          "csheth !! cs.stonybrook.edu"
  # Social networking links used in footer. Update and remove as you like.
  github: chintak
  bitbucket: chintak
  stackoverflow_id:
  twitter: chintaksheth
  linkedin: chintaksheth

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: true
extended_fonts: false
enable_anchorjs: false
permalink:    pretty
sass:
  compressed: true
